# -*- coding: utf-8 -*-
"""Tuto_5.1_Introduction_to_parameter_estimation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/gw-odw/odw/blob/main/Tutorials/05_Parameter_Estimation/Tuto_5.1_Introduction_to_parameter_estimation.ipynb

<span style="float: left;padding: 1.3em">![logo](https://github.com/gw-odw/odw/blob/main/Tutorials/logo.png?raw=1)</span>


# Gravitational Wave Open Data Workshop

## Tutorial 5.1: An introduction to parameter estimation

In this tutorial, we will introduce Bayesian inference and "parameter estimation", a crucial part of gravitational wave astronomy. We will start with a general introduction to inference, the idea of stochastic sampling, and then introduce the
[bilby Bayesian inference library](https://lscsoft.docs.ligo.org/bilby/).

View this tutorial on [Google Colaboratory](https://colab.research.google.com/github/gw-odw/odw/blob/main/Tutorials/05_Parameter_Estimation/Tuto_5.1_Introduction_to_parameter_estimation.ipynb) or launch [mybinder](https://mybinder.org/v2/gh/gw-odw/odw/HEAD).

## Installation (execute only if running on a cloud platform, like Google Colab, or if you haven't done the installation already!)

> ⚠️ **Warning**: restart the runtime after running the cell below.
>
> To do so, click "Runtime" in the menu and choose "Restart and run all".
>
> You may see error messages but installation usually works.
> If you experience problems, please [report an issue](https://github.com/gw-odw/odw/issues).
"""

# -- Use the following line in Google Colab
! pip install -U -q bilby==2.6.0 dynesty==2.1.5 corner==2.2.3

"""### Download sample data

If you are running on Google Colab, or another environment which copies the notebook but not the sample data. Please run the following cell. (Note: you may also download the file directly).
"""

import os
if not os.path.isfile("toy_model.csv"):
  print("Downloading toy_model.csv")
  ! wget --no-verbose https://raw.githubusercontent.com/gw-odw/odw/main/Tutorials/05_Parameter_Estimation/toy_model.csv
else:
  print("toy_model.csv exists; not downloading")

import numpy as np
# The first import of matplotlib can take some time (especially on cloud platforms). This is normal.
import matplotlib
import matplotlib.pyplot as plt
import bilby
import corner

# Make bilby more terse
bilby.core.utils.log.setup_logger(log_level='WARNING')

for module in [np, matplotlib, bilby, corner]:
    print(f"Loaded {module.__name__}: {module.__version__}")

"""### Bayesian inference

Let us assume we are given some data $d$ and we wish to use the data to learn about a model $M$ with associated parameters $\theta$. Bayes' theorem provides a framework to do this. Namely, the *posterior* probability distribution of the parameters $\theta$ can be calculated from

$$ p(\theta | d, M) = \frac{\mathcal{L}(d| \theta, M) \;\pi(\theta | M)}{\mathcal{Z}(d | M)} $$

where $\mathcal{L}(d| \theta, M)$ is the *likelihood*, $\pi(\theta | M)$ is the *prior* probability distribution, and $\mathcal{Z}(d | M)$ is the *evidence* (or fully marginalized likelihood) which normalized the posterior, i.e.

$$ \mathcal{Z}(d | M) = \int \mathcal{L}(d| \theta, M) \;\pi(\theta | M)\, d\theta $$

For most interesting problems, the posterior and evidence (i.e. $p(\theta | d, M) $ and $\mathcal{Z}(d | M) $) cannot be calculated in closed form. Instead we rely on computational methods to approximate them - in this tutorials we will use **stochastic sampling**.

Approximating $p(\theta | d, M)$ is known as **parameter estimation** for obvious reasons. However, let us briefly note that Bayesian inference also extends to **model comparison** as follows. If we have two models, say $M_A$ and $M_B$, then Bayes theorem also tells us that

$$ \frac{P(M_A | d)}{P(M_B | d)} = \frac{\mathcal{Z}(d | M_A)}{\mathcal{Z}(d | M_B)} \frac{\pi(M_A)}{\pi(M_B)} $$

This ratio known as the *posterior odds* compares the relative probability of each model. If it is greater than 1 this implies evidence for $M_A$ whereas if it is less than 1 it implies evidence for $M_B$. The right hand side is the product of the *Bayes factor* $\frac{\mathcal{Z}(d | M_A)}{\mathcal{Z}(d | M_B)}$ (which can be estimated using stochastic sampling) and the *prior odds* $\frac{\pi(M_A)}{\pi(M_B)}$.

### Introducing a toy model

In order to introduce the basics of Bayesian inference and stochastic sampling, let us introduce some example data and then a toy model with parameters for us to estimate. In this repository, we include our data `toy_model.csv`. This is a text file containing an observed timeseries of `yobs` recorded at times `time`. We now read in the data and plot it
"""

time, yobs = np.genfromtxt("toy_model.csv", delimiter=",").T
fig, ax = plt.subplots()
ax.plot(time, yobs)
ax.set(xlabel="Time [s]", ylabel="Observed y values [arb. units]")
plt.show()

"""We are told by our theorist colleague, that a good model to explain this data is a so-called *sine Gaussian* which consists of a sinusoidal function modulated with a Gaussian-exponential envelope, i.e.

$$ M_s: s(t) = e^{-(t/\alpha)^2} \sin\left(2\pi f t\right)  $$

where $M_s$ will be our label for the sine-Gaussian model. This model has two parameters $f$ and $\alpha$; we could further generalise this to have an arbitrary amplitude, phase shift, or time shift, as well but here we introduce the simple two-parameter model for illustration.

Before we go any further, let's check that we understand the model by plotting it out with some arbitrary choices for $f$ and $\alpha$. To do this, we will create some functions that we can use later on. We plot the full function and the individual components to help visualise it.
"""

def sinusoid(time, freq):
    return np.sin(2 * np.pi * freq * time)


def gaussian_exponential(time, alpha):
    return np.exp(-(time/alpha)**2)


def model_Ms(time, freq, alpha):
    return gaussian_exponential(time, alpha) * sinusoid(time, freq)

freq = 2
alpha = 0.5

fig, ax = plt.subplots()

ax.plot(time, sinusoid(time, freq), label="Sinusoid")
ax.plot(time, gaussian_exponential(time, alpha), label="Gaussian exponential")
ax.plot(time, model_Ms(time, freq, alpha), label="Sine Gaussian")
ax.set(xlabel="Time [s]", ylabel="Observed y values [arb. units]")
ax.legend()
plt.show()

"""### Parameter Estimation

Now that we have our data (`yobs`) and our model $M_s$, our task is to estimate the parameters $f$ and $\alpha$. To do this, we will use Bayes theorem, i.e. we want to approximate the distribution

$$ p(\theta | d, M_s) = \frac{\mathcal{L}(d| \theta, M_s) \;\pi(\theta | M_s)}{\mathcal{Z}(d | M_s)} $$

where $\theta=\{f, \alpha\}$ is the two-dimensional parameter vector and $d$ is `yobs` (measured at times `time`). To this end, we need to define the likelihood and priors. Note that, if we are **only interested in the shape of the distribution**, then we can ignore the evidence, i.e. we can estimate the unnormalized distribution

$$ p(\theta | d, M_s) \propto \mathcal{L}(d| \theta, M_s) \;\pi(\theta | M_s) $$

Before proceeding, we need to define our likelihood and prior.

#### Parameter Estimation: Likelihood

For this toy example, we will assume that the data consists of the generate model $M_s$ and additive white Gaussian noise, i.e.

$$ y_{\rm obs}(t) = s(t; f, \alpha) + \epsilon $$

where $\epsilon \sim N(0, \sigma)$ by which we mean that $\epsilon$ is drawn from a Gaussian distribution with zero mean and standard deviation $\sigma=0.1$ (for now, we will assume this is known a priori, but see challenges below for how it could be estimated).

This definition of how the data was created allows us to define our likelihood. Namely, given a value of $\{f, \alpha\}$, the likelihood of a single data point $y_i$ (measured at $t_i$) is:

$$ \mathcal{L}(y_i| f, \alpha, M_s) = \frac{1}{\sqrt{2\pi \sigma^2}} \exp\left(-\frac{(y_i - s(t_i; f, \alpha))^2}{2\sigma^2}\right) $$

To extend this to multiple data points, we assume they are independent then

$$ \mathcal{L}(y_{obs} | f, \alpha, M_s) = \prod_i \mathcal{L}(y_i| f, \alpha, M_s) $$

In practice, it is wise to work with the logarithm of the likelihood to avoid numerical overflow. Then, we have that

$$ \log \mathcal{L}(y_{obs} | f, \alpha, M_s) = \sum_{i} -\frac{1}{2}\left(\frac{\left(y_i - s(t_i; f, \alpha)\right)^2}{\sigma^2} + \log\left(2\pi \sigma^2\right)\right) $$

We now transcribe this into `python`:
"""

def log_likelihood_Ms(time, yobs, freq, alpha, sigma=0.1):
    prediction = model_Ms(time, freq, alpha)
    res = yobs - prediction
    logl = -0.5 * (((res/sigma)**2) + np.log(2 * np.pi * sigma**2))
    # Sum over all log_likelihoods (axis=0)
    return np.sum(logl, axis=0)

"""#### Parameter Estimation: Priors

The second part of Bayes theorem is the *prior*. For our two-component model, we will use a simple disjoint prior (i.e. $\pi(\theta | M_s)=\pi(f| M_s)\pi(\alpha | M_s)$) with

$$ \pi(f| M_s) = \textrm{Uniform}(0, 5) $$
$$ \pi(\alpha| M_s) = \textrm{Uniform}(0, 1) $$

Let us create a python function to calculate the log of the prior:
"""

def log_prior_Ms(freq, alpha):
    """ Calculate the log prior under the Ms model

    Parameters
    ----------
    freq: array or float
        The frequency at which to calculate the prior
    alpha: array or float
        The alpha at which to calculate the prior

    Returns
    -------
    log_prior: array
        The log_prior calculated for all freq, alpha samples
    """
    # Convert freq, alpha to numpy arrays
    freq = np.atleast_1d(freq)
    alpha = np.atleast_1d(alpha)

    # Apply Uniform priors: calculate idxs of array where f, alpha in range
    f_min = 0
    f_max = 5
    f_idxs = (freq > f_min) * (freq < f_max)

    alpha_min = 0
    alpha_max = 1
    alpha_idxs = (alpha > alpha_min) * (alpha < alpha_max)

    idxs = alpha_idxs * f_idxs

    log_prior_volume = np.log(1/(f_max - f_min) * (1 / (alpha_max - alpha_min)))

    log_prior = np.zeros_like(freq)
    log_prior[idxs] = log_prior_volume
    log_prior[~idxs] = -np.inf
    return log_prior

"""#### Parameter Estimation: Rejection Sampling

Now that we have our likelihood and prior, we will introduce **stochastic sampling**. We start by using the simplest type of stochastic sampling, rejection sampling. The idea is that to draw samples from a target distribution $p(\theta | d, M_s)$ which is difficult to sample from, we first generate samples from a generating distribution $g(\theta$) which is easy to sample from and then weight the samples relative to the target distribution. In practice you can choose any generating distribution you like, but we will use $g(\theta) = g(f)g(\alpha)$ where

$$ g(f) = \textrm{Uniform}(1.8, 2.2) $$
$$ g(\alpha) = \textrm{Uniform}(0.2, 0.6) $$

Our rejection sampling algorithm then proceeds as follows:


1. Draw $\theta'=[f, \alpha]$ from $g(f)$ and $g(\alpha)$
2. Calculate the probability under the target and generating distributions (i.e. $p(\theta' | d, M_s)$ and $g(\theta')$)
3. Calculate the weight $w=p(\theta' | d, M_s) / g(\theta')$
4. Draw a random number $u$ uniformly distributed in $[0, 1]$
5. If $w > u$, append $\theta'$ to a set of samples, otherwise reject it and repeat

Continue this loop until an acceptable number of samples have been drawn. The resulting set of samples are then an approximation to $p(\theta | d, M_s)$ and be used to produce summary statistics or create plots.

We now program the algorithm for our test data. However, there are two important differences between this algorithm and the expression above:

1. We will work with the unnormalised distribution $p(\theta | d, M_s)$ (i.e. we don't calculate the evidence $\mathcal{Z}$. As a result, $w$ is also unnormalised and so it needs to be normalised before we apply step 5. Fortunately, we can normalize $w$ once we have a distribution of values.  
2. For computational efficiency, rather than using a while loop we will instead draw a set of 100,000 samples, calculate the weights for each, and then apply rejection sampling. This utilises numpy array optimization and also enables us to normalise the weights to a distribution.
"""

# Draw 100,000 samples from g(theta)
N = 100000
freq_gsamples = np.random.uniform(1.8, 2.2, N)
alpha_gsamples = np.random.uniform(0.2, 0.6, N)

# Make time a 2D array to enable broadcasting across the samples
time_array = time[:, np.newaxis]
yobs_array = yobs[:, np.newaxis]

# Calculate the log_likelihood and log_prior for all samples
log_likelihood_vals = log_likelihood_Ms(time_array, yobs_array, freq_gsamples, alpha_gsamples)
log_prior_vals = log_prior_Ms(freq_gsamples, alpha_gsamples)
log_posterior_vals = log_likelihood_vals + log_prior_vals

# Calculate the weights
weights = np.exp(log_posterior_vals)

# Normalise the weights
weights = weights / max(weights)

# Rejection sample
keep = weights > np.random.uniform(0, 1, weights.shape)
alpha_samples = alpha_gsamples[keep]
freq_samples = freq_gsamples[keep]

"""The end result of this is a set of samples `freq_samples` and `alpha_samples` that approximate the posterior distribution. We can get a quick visualisation of these by using the `corner` package:"""

# Create a corner plot
samples = np.array([freq_samples, alpha_samples]).T
fig = corner.corner(samples, bins=20, labels=["f", "alpha"], show_titles=True, quantiles=[0.16, 0.5, 0.84],)

"""The plot above shows two 1D histograms (one for each parameter) and one 2D histogram (showing any correlations between the samples). Areas where the posterior is large (i.e. the histogram count is high) represent the most probable values of $f$ and $\alpha$ which explain the data.

The samples can also be used to provide a summary statistic. For example, if you wanted to report the mean and standard deviation interval for $f$, you could do something like this:
"""

mean_f = np.mean(freq_samples)
std_f = np.std(freq_samples)
print(f"We estimate the mean and standard deviation of frequency to be {mean_f:0.2f}+/-{std_f:0.2f}")

"""Typically, in GW astronomy, we use the median and a 90\% credible interval because the posterior is often non-symmetric.

In this exercise, we have learned that rejection sampling can be used to approximate the posterior distribution. However, we should note that it is highly inefficienct. It works okay here, because we tightly tuned the edges of $g(\theta)$, but if you go back and increase these to a wider range, you'll see the efficiency quickly drops off. Moreover, the efficiency of rejection sampling also suffers when we start to look at problems in more than 2 parameters.
"""

# To calculate the efficiency
efficiency = len(freq_samples) / len(freq_gsamples)
print(efficiency)

"""#### Parameter Estimation: Markov Chain Monte Carlo

The rejection sampling algorithm is inefficient in problems where the posterior is small compared to the prior volume. To address this, a range of stochastic sampling algorithms are available. In GW astronomy, two are preferred: Markov Chain Monte Carlo (MCMC), and Nested Sampling. We will now introduce `bilby` which is an inference package allowing access to several off the shelf samplers.

`bilby` has helper functionality to program up our likelihood and prior. We begin by using that:
"""

likelihood_Ms = bilby.core.likelihood.GaussianLikelihood(time, yobs, model_Ms, sigma=0.1)

priors_Ms = dict(
    freq=bilby.core.prior.Uniform(0, 5),
    alpha=bilby.core.prior.Uniform(0, 1)
)

"""This creates two objects, a `likelihood` and `prior`. These can now be passed to `run_sampler` with some options to select the `bilby_mcmc` sampler and configure it in a way that is efficient for this problem."""

result_Ms = bilby.run_sampler(
    likelihood_Ms,
    priors_Ms,
    label="model_Ms",  # A label to help sort our results
    outdir="toy_model",  # The directory where results will be kept
    clean=True,  # Don't use cached data
    sampler="bilby_mcmc",  # Use the bilby_mcmc sampler
    nsamples=1000,  # Draw 1000 samples
    printdt=2,  # Print an update ever 5 seconds
    L1steps=1,  # The number of internal steps to take
)

"""The `run_sampler` method returns an object `result`. This contains all the interesting information that we might want to use. It also has methods we can use. For example, let's create a corner plot."""

result_Ms.plot_corner()

"""We can also get to the samples, which are stored as a `pandas` data frame, as follows"""

result_Ms.posterior

"""Let's compare our rejection sampling results with the `bilby_mcmc` results. To do this, we will create a histogram of the $f$ samples for both:"""

fig, ax = plt.subplots()
ax.hist(freq_samples, density=True, bins=50, label="Rejection Sampling", alpha=0.8)
ax.hist(result_Ms.posterior["freq"], density=True, bins=50, label="bilby_mcmc", alpha=0.5)
ax.set(xlabel="f", ylabel="Density")
plt.legend()
plt.show()

"""They lie on top of each other: this indicates that, within sampling errors, they are producing identical results.

## Quiz Questions

### Question 1

To quantify agreement between distributions,  it is often useful to calculate a summary statistic and show they agree. Calculate the mean and standard deviation from the rejection sampling algorithm **and** the `bilby_mcmc` approach for both $f$ and $\alpha$. Do they agree to within the quoted standard deviation?
"""

print('Rejection Sampling Results:')
mean_f_rejection = np.mean(freq_samples)
std_f_rejection = np.std(freq_samples)
mean_alpha_rejection = np.mean(alpha_samples)
std_alpha_rejection = np.std(alpha_samples)
print(f"  Frequency: Mean = {mean_f_rejection:.4f}, Std = {std_f_rejection:.4f}")
print(f"  Alpha: Mean = {mean_alpha_rejection:.4f}, Std = {std_alpha_rejection:.4f}")

print('\nBilby MCMC Results:')
mean_f_mcmc = np.mean(result_Ms.posterior["freq"])
std_f_mcmc = np.std(result_Ms.posterior["freq"])
mean_alpha_mcmc = np.mean(result_Ms.posterior["alpha"])
std_alpha_mcmc = np.std(result_Ms.posterior["alpha"])
print(f"  Frequency: Mean = {mean_f_mcmc:.4f}, Std = {std_f_mcmc:.4f}")
print(f"  Alpha: Mean = {mean_alpha_mcmc:.4f}, Std = {std_alpha_mcmc:.4f}")

# Check for agreement within standard deviation
print('\nAgreement Check:')
# For frequency
if abs(mean_f_rejection - mean_f_mcmc) <= (std_f_rejection + std_f_mcmc):
    print("  Frequency means agree within their combined standard deviations.")
else:
    print("  Frequency means do NOT agree within their combined standard deviations.")

# For alpha
if abs(mean_alpha_rejection - mean_alpha_mcmc) <= (std_alpha_rejection + std_alpha_mcmc):
    print("  Alpha means agree within their combined standard deviations.")
else:
    print("  Alpha means do NOT agree within their combined standard deviations.")

"""### Question 2

Having the posterior distributions tells us about the parameters, but not if the model is a good fit to the data. For this, it is useful to use a *posterior predictive check*. Create a plot of the raw data (i.e `yobs` against `time`) Then, overlay on it the prediction of your model using the mean for $f$ and $\alpha$ estimated in Q1 (from either method).
"""

fig, ax = plt.subplots()
ax.plot(time, yobs, label='Raw Data', color='C0')

# Get the mean values for f and alpha from bilby_mcmc results (from Q1)
mean_f = np.mean(result_Ms.posterior["freq"])
mean_alpha = np.mean(result_Ms.posterior["alpha"])

# Generate model prediction using these mean values
model_prediction_mean = model_Ms(time, mean_f, mean_alpha)
ax.plot(time, model_prediction_mean, label=f'Mean Estimate (f={mean_f:.2f}, alpha={mean_alpha:.2f})', linestyle='--', color='C1', linewidth=2)

# Calculate and plot the maximum likelihood fit
idx_max = np.argmax(result_Ms.posterior.log_likelihood)
maxL = result_Ms.posterior.iloc[idx_max]
f_max_L = maxL.freq
alpha_max_L = maxL.alpha
model_prediction_maxL = model_Ms(time, f_max_L, alpha_max_L)
ax.plot(time, model_prediction_maxL, label=f'Maximum Likelihood (f={f_max_L:.2f}, alpha={alpha_max_L:.2f})', linestyle=':', color='C2', linewidth=2)
plt.title('Model vs data overlay')

"""### Question 3 (Optional)

It is more common to show the maximum likelihood fit and some measure of uncertainty. For the maximum likelihood, this can be obtained from the `posterior` data frame as follow:

- First identify the index of the maximum likelihood point `idx_max = np.argmax(result_Ms.posterior.log_likelihood)`
- Then return the row of the maximum `maxL = result_Ms.posterior.iloc[idx_max]`
- The values can be accessed with `maxL.freq` for example

A straightforward approach is to draw random samples from $p(\theta| d, M_s)$ and plot these. You can draw a random sample from the bilby posterior using `result.posterior.sample().iloc[0]` (this will give you a single sample with keys for `freq` and `alpha`). Draw 100 samples from the posterior and overplot them alongside your mean estimate. You will want to add `color='C3'`, `zorder=-100` and `alpha=0.1` to the `plot()` command so they don't overwhelm the rest of the plot.
"""

fig, ax = plt.subplots()
ax.plot(time, yobs, label='Raw Data', color='C0')

# Get the mean values for f and alpha from bilby_mcmc results (from Q1)
mean_f = np.mean(result_Ms.posterior["freq"])
mean_alpha = np.mean(result_Ms.posterior["alpha"])

# Generate model prediction using these mean values
model_prediction_mean = model_Ms(time, mean_f, mean_alpha)
ax.plot(time, model_prediction_mean, label=f'Mean Estimate', color='C1', linewidth=2)

# Calculate and plot the maximum likelihood fit
idx_max = np.argmax(result_Ms.posterior.log_likelihood)
maxL = result_Ms.posterior.iloc[idx_max]
f_max_L = maxL.freq
alpha_max_L = maxL.alpha
model_prediction_maxL = model_Ms(time, f_max_L, alpha_max_L)
# Draw 100 random samples from the posterior and overplot them
for i in range(100):
    sample = result_Ms.posterior.sample().iloc[0]
    f_sample = sample.freq
    alpha_sample = sample.alpha
    model_sample_prediction = model_Ms(time, f_sample, alpha_sample)
    ax.plot(time, model_sample_prediction, color='C3', zorder=-100, alpha=0.1)

ax.set(xlabel="Time [s]", ylabel="Observed y values [arb. units]")
ax.legend()
plt.title('Posterior Predictive Check with Uncertainty')
plt.show()

"""### Question 4 (Optional: hard)

Your plot from Q2 should tell you that the model isn't fully explaining the data! You take the plot back to your theorist colleague and demand an explanation. They quickly tell you that actually there is a better model where the frequency of the sinusoid is time-dependent:

$$ M_t: s(t) = e^{-(t/\alpha)^2} \sin\left(2\pi (f_0 + \dot{f} \times t) t\right)  $$

This new model has three parameters: $f$, $\dot{f}$ and $\alpha$.

Your task is to program this model in a new function, then run `bilby_mcmc` on it and reproduce the figure from Q3. You will need to define new parameters $f_0$ and $\dot{f}$ in the function (probably best to call it `model_Mt` to be consistent) and add these to the prior. If you are successful, the predicted plot should nicely overlap the data. Along the way you should also create a corner plot: this can be helpful to see if you have chosen appropriate priors.
"""

def model_Mt(time, f0, f_dot, alpha):
    return gaussian_exponential(time, alpha) * np.sin(2 * np.pi * (f0 + f_dot * time) * time)

def log_likelihood_Mt(time, yobs, f0, f_dot, alpha, sigma=0.1):
    prediction = model_Mt(time, f0, f_dot, alpha)
    res = yobs - prediction
    logl = -0.5 * (((res/sigma)**2) + np.log(2 * np.pi * sigma**2))
    return np.sum(logl, axis=0)

"""Now, let's define the priors for the new model and run `bilby_mcmc`."""

likelihood_Mt = bilby.core.likelihood.GaussianLikelihood(time, yobs, model_Mt, sigma=0.1)

priors_Mt = dict(
    f0=bilby.core.prior.Uniform(0, 5, name='f0', latex_label='$f_0$'),
    f_dot=bilby.core.prior.Uniform(-1, 1, name='f_dot', latex_label='$\\dot{f}$'),
    alpha=bilby.core.prior.Uniform(0, 1, name='alpha', latex_label=r'$\alpha$')
)

result_Mt = bilby.run_sampler(
    likelihood_Mt,
    priors_Mt,
    label="model_Mt",
    outdir="toy_model",
    clean=True,
    sampler="bilby_mcmc",
    nsamples=1000,
    printdt=2,
    L1steps=1,
)

"""Here is the corner plot for the new model's parameters."""

result_Mt.plot_corner()

"""Finally, let's reproduce the posterior predictive check plot from Question 3 using the results from `model_Mt`."""

fig, ax = plt.subplots()
ax.plot(time, yobs, label='Raw Data', color='C0')

# Get the mean values for f0, f_dot, and alpha from bilby_mcmc results
mean_f0 = np.mean(result_Mt.posterior["f0"])
mean_f_dot = np.mean(result_Mt.posterior["f_dot"])
mean_alpha = np.mean(result_Mt.posterior["alpha"])

# Generate model prediction using these mean values
model_prediction_mean_Mt = model_Mt(time, mean_f0, mean_f_dot, mean_alpha)
ax.plot(time, model_prediction_mean_Mt, label=f'Mean Estimate Mt', color='C1', linewidth=2)

# Calculate and plot the maximum likelihood fit for Mt
idx_max_Mt = np.argmax(result_Mt.posterior.log_likelihood)
maxL_Mt = result_Mt.posterior.iloc[idx_max_Mt]
f0_max_L_Mt = maxL_Mt.f0
f_dot_max_L_Mt = maxL_Mt.f_dot
alpha_max_L_Mt = maxL_Mt.alpha
model_prediction_maxL_Mt = model_Mt(time, f0_max_L_Mt, f_dot_max_L_Mt, alpha_max_L_Mt)
ax.plot(time, model_prediction_maxL_Mt, label=f'Maximum Likelihood Mt', linestyle=':', color='C2', linewidth=2)

# Draw 100 random samples from the posterior and overplot them for Mt
for i in range(100):
    sample_Mt = result_Mt.posterior.sample().iloc[0]
    f0_sample_Mt = sample_Mt.f0
    f_dot_sample_Mt = sample_Mt.f_dot
    alpha_sample_Mt = sample_Mt.alpha
    model_sample_prediction_Mt = model_Mt(time, f0_sample_Mt, f_dot_sample_Mt, alpha_sample_Mt)
    ax.plot(time, model_sample_prediction_Mt, color='C3', zorder=-100, alpha=0.1)

ax.set(xlabel="Time [s]", ylabel="Observed y values [arb. units]")
ax.legend()
plt.title('Posterior Predictive Check with Uncertainty for Model Mt')
plt.show()

"""### Question 5 (Optional)

We can tell already that the $M_t$ model is far better than $M_s$: the posterior predictive fit better explains the data. One can also look at the posterior of $\dot{f}$ from $M_t$: Since $M_s$ is a subset of $M_t$ (i.e. they are equivalent when $\dot{f}=0$) the fact that the posterior on $\dot{f}$ peaks away from zero tells you that $M_t$ is better than $M_s$.

However, it is fun to also show how we can quantify this using the posterior odds (defined in the first section!). For this, we need to calculate the evidence $\mathcal{Z}(d | M_s)$ and $\mathcal{Z}(d | M_t)$. They can be estimated by stochastic sampling. However, `bilby_mcmc` is not the right tool (in can in principle, but the alternative is superior for evidence calculation). Instead, we should use the **nested sampling** package `dynesty`

- Rerun your analysis of both models, but use `sampler="dynesty"` in `run_sampler`. You will also need to add configuration arguments: `nlive=500, sample="rwalk"`)
- Calculate the Bayes factor using `np.exp(result_Mt.log_evidence - result_Ms.log_evidence)`
"""

result_Ms = bilby.run_sampler(
    likelihood_Ms,
    priors_Ms,
    label="model_Ms",  # A label to help sort our results
    outdir="toy_model",  # The directory where results will be kept
    clean=True,  # Don't use cached data
    sampler="bilby_mcmc",  # Use the bilby_mcmc sampler
    nsamples=1000,  # Draw 1000 samples
    printdt=2,  # Print an update ever 5 seconds
    L1steps=1,  # The number of internal steps to take
)

"""### Running Nested Sampling with `dynesty` for Model Ms"""

result_Ms_dynesty = bilby.run_sampler(
    likelihood_Ms,
    priors_Ms,
    label="model_Ms_dynesty",  # A new label for clarity
    outdir="toy_model",
    clean=True,
    sampler="dynesty",  # Use dynesty sampler
    nlive=500,  # Number of live points
    sample="rwalk",  # Sampling method
    printdt=2,
)

"""### Running Nested Sampling with `dynesty` for Model Mt"""

result_Mt_dynesty = bilby.run_sampler(
    likelihood_Mt,
    priors_Mt,
    label="model_Mt_dynesty",  # A new label for clarity
    outdir="toy_model",
    clean=True,
    sampler="dynesty",  # Use dynesty sampler
    nlive=500,  # Number of live points
    sample="rwalk",  # Sampling method
    printdt=2,
)

"""### Calculating the Bayes Factor"""

# The log evidence is stored in the result object
log_evidence_Ms = result_Ms_dynesty.log_evidence
log_evidence_Mt = result_Mt_dynesty.log_evidence

bayes_factor = np.exp(log_evidence_Mt - log_evidence_Ms)

print(f"Log Evidence for Model Ms (dynesty): {log_evidence_Ms:.2f}")
print(f"Log Evidence for Model Mt (dynesty): {log_evidence_Mt:.2f}")
print(f"Bayes Factor (Mt/Ms): {bayes_factor:.2e}")

# Estimate sigma from the first 1 second of data (time from -2 to -1)
first_second_mask = (time >= -2) & (time <= -1)
yobs_first_second = yobs[first_second_mask]
sigma_estimate_first_second = np.std(yobs_first_second)

# Estimate sigma from the last 1 second of data (time from 1 to 2)
last_second_mask = (time >= 1) & (time <= 2)
yobs_last_second = yobs[last_second_mask]
sigma_estimate_last_second = np.std(yobs_last_second)

print(f"Estimated sigma from the first second of data: {sigma_estimate_first_second:.4f}")
print(f"Estimated sigma from the last second of data: {sigma_estimate_last_second:.4f}")
print(f"True sigma value: 0.1")

# Check if they are close to the true value
if np.isclose(sigma_estimate_first_second, 0.1, atol=0.01):
    print("The estimate from the first second is close to the true value.")
else:
    print("The estimate from the first second is NOT close to the true value.")

if np.isclose(sigma_estimate_last_second, 0.1, atol=0.01):
    print("The estimate from the last second is close to the true value.")
else:
    print("The estimate from the last second is NOT close to the true value.")

"""### Question 6 (Optional: easy)

Throughout all our analyses, we assumed that $\sigma=0.1$. But, what would we do if we didn't know this a priori? One option is to estimate it, you can do this by simply taking the standard deviation of data away from where the transient signal is. First, try to cut out the first 1s of data and use this to estimate $\sigma$, is it close to the true value $0.1$? How about taking the last second of data?
"""

# Estimate sigma from the first 1 second of data (time from -2 to -1)
first_second_mask = (time >= -2) & (time <= -1)
yobs_first_second = yobs[first_second_mask]
sigma_estimate_first_second = np.std(yobs_first_second)

# Estimate sigma from the last 1 second of data (time from 1 to 2)
last_second_mask = (time >= 1) & (time <= 2)
yobs_last_second = yobs[last_second_mask]
sigma_estimate_last_second = np.std(yobs_last_second)

print(f"Estimated sigma from the first second of data: {sigma_estimate_first_second:.4f}")
print(f"Estimated sigma from the last second of data: {sigma_estimate_last_second:.4f}")
print(f"True sigma value: 0.1")

# Check if they are close to the true value
if np.isclose(sigma_estimate_first_second, 0.1, atol=0.01):
    print("The estimate from the first second is close to the true value.")
else:
    print("The estimate from the first second is NOT close to the true value.")

if np.isclose(sigma_estimate_last_second, 0.1, atol=0.01):
    print("The estimate from the last second is close to the true value.")
else:
    print("The estimate from the last second is NOT close to the true value.")

"""### Question 7 (Optional: harder)

If we did not know $\sigma$ a priori, and we didn't trust our estimate, we could simply infer it from the data! You can do this by removing the `sigma=0.1` in the `GaussianLikelihood` and setting a prior on sigma. Try this using your $M_t$ model.
"""

# Redefine likelihood_Mt without a fixed sigma
likelihood_Mt_inferred_sigma = bilby.core.likelihood.GaussianLikelihood(time, yobs, model_Mt)

# Redefine priors_Mt to include a prior for sigma
priors_Mt_inferred_sigma = dict(
    f0=bilby.core.prior.Uniform(0, 5, name='f0', latex_label='$f_0$'),
    f_dot=bilby.core.prior.Uniform(-1, 1, name='f_dot', latex_label='$\dot{f}$'),
    alpha=bilby.core.prior.Uniform(0, 1, name='alpha', latex_label=r'$\alpha$'),
    sigma=bilby.core.prior.Uniform(0.01, 1, name='sigma', latex_label='$\sigma$') # Prior for inferred sigma
)

# Run the sampler for model_Mt, inferring sigma
result_Mt_inferred_sigma = bilby.run_sampler(
    likelihood_Mt_inferred_sigma,
    priors_Mt_inferred_sigma,
    label="model_Mt_inferred_sigma",
    outdir="toy_model",
    clean=True,
    sampler="dynesty",
    nlive=500,
    sample="rwalk",
    printdt=2,
)

# Plot the corner plot for the new results
result_Mt_inferred_sigma.plot_corner()